### ISSUE TITLE
select_display.cpp run error

### ISSUE THREAD

**Issue by gouchaoer** [Fadis/gct#2]
Vulkan 1.3.239
Min image count: 2
Max image count: 8

利用可能なフォーマット : A8B8G8R8UnormPack32
利用可能なフォーマット : A8B8G8R8SrgbPack32
利用可能なフォーマット : A2B10G10R10UnormPack32
利用可能なフォーマット : A1R5G5B5UnormPack16
利用可能なフォーマット : B8G8R8A8Unorm
サーフェスの最小イメージ数 : 2
サーフェスの最大イメージ数 : 8
terminate called after throwing an instance of 'vk::UnknownError'
  what():  vk::Device::createSwapchainKHRUnique: ErrorUnknown
Aborted (core dumped)

**Comment by Fadis** [comment]
Thank you for reporting an issue.
The most common reason of those error messages is that the process failed to acquire the display.
Since X server (or Wayland compositor) acquires the display, if you run select_display on X window system, select_display will fail to take same display.
All sample programs with "VK_KHR_display" instance extension (This extension requires exclusive control on a display) need to be executed on a host that X(or Wayland) is not running.

**Comment by gouchaoer** [comment]
> 

I have two monitors plugged to my Linux.
After I restarted my ubuntu18.08, everything is OK like miracle.
I didn't stop X server and login the desktop as usual.
thank you so much
